# Generated by Django 5.1.7 on 2025-03-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='img')),
                ('descripition', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.TextField(blank=True, choices=[('Clothings', 'CLOTHINGS'), ('Eletronics', 'ELETRONICS'), ('Books', 'BOOKS')], max_length=15, null=True)),
            ],
        ),
    ]
