# Generated by Django 5.2 on 2025-04-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripition',
            new_name='description',
        ),
    ]
